name: 'Delete Release Assets By Tag'
description: 'Deletes all of the assets in a release specified by the tag name'
author: 'Jérôme von Daak'
inputs:
  asset_tag:
    description: 'The Tag of the release we are searching for'
    required: true
  asset_owner:
    description: 'The Owner of the repo. If not specified, it gets the owner from context'
    required: false
  asset_repo:
    description: 'The Repository this is called for. If not specified it get the repository from context'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'delete'
  color: 'red'